on: push

jobs:
  run:
    runs-on: ubuntu-latest
    name: Run karate-slim
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Run it
      run: sh run.sh
    - name: upload result
      uses: actions/upload-artifact@v3
      with:
        name: results
        path: results/
